apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://gitea.applications.svc.cluster.local:3000/remotelab
    chart: django-app
    targetRevision: "*"
    helm:
      valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
