apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitea.homelab.local/homelab/manifests.git
    targetRevision: HEAD
    path: manifests/applications
    directory:
      include: "{redis.yaml,django.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # Manual sync for applications initially
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas