name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: gitea:3000
  IMAGE_NAME: django-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          FORCE_SCRIPT_NAME: ''
        run: |
          python manage.py test

      - name: Check code style
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: gitea.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine version
        id: version
        run: |
          # Extract base version from version.py
          BASE_VERSION=$(grep "BASE_VERSION = " version.py | cut -d'"' -f2)
          # Create semantic version using build number
          SEMVER="${BASE_VERSION}.${{ gitea.run_number }}"
          echo "semver=${SEMVER}" >> $GITHUB_OUTPUT
          echo "base_version=${BASE_VERSION}" >> $GITHUB_OUTPUT
          echo "Tagging version: ${SEMVER}"

      - name: Configure Docker credentials
        run: |
          # Create docker config directly to bypass token auth flow
          mkdir -p ~/.docker
          AUTH=$(echo -n "${{ gitea.actor }}:${{ secrets.REGISTRY_TOKEN }}" | base64 -w 0)
          cat > ~/.docker/config.json << EOF
          {
            "auths": {
              "${{ env.REGISTRY }}": {
                "auth": "${AUTH}"
              }
            }
          }
          EOF
          echo "Docker credentials configured for ${{ env.REGISTRY }}"

      - name: Extract metadata
        id: meta
        run: |
          GITEA_IMAGE="${{ env.REGISTRY }}/${{ gitea.repository_owner }}/${{ env.IMAGE_NAME }}"
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "image=${GITEA_IMAGE}" >> $GITHUB_OUTPUT
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            --build-arg APP_VERSION=${{ steps.version.outputs.semver }} \
            --build-arg BUILD_COMMIT=${{ gitea.sha }} \
            --build-arg BUILD_DATE=${{ steps.meta.outputs.build_date }} \
            -t ${{ steps.meta.outputs.image }}:${{ steps.version.outputs.semver }} \
            -t ${{ steps.meta.outputs.image }}:latest \
            .

      - name: Push to registry
        run: |
          # Install skopeo (handles auth without token flow issues)
          apt-get update -qq && apt-get install -y -qq skopeo > /dev/null
          # Push images using skopeo with explicit credentials
          skopeo copy --dest-tls-verify=false \
            --dest-creds="${{ gitea.actor }}:${{ secrets.REGISTRY_TOKEN }}" \
            docker-daemon:${{ steps.meta.outputs.image }}:${{ steps.version.outputs.semver }} \
            docker://${{ steps.meta.outputs.image }}:${{ steps.version.outputs.semver }}
          skopeo copy --dest-tls-verify=false \
            --dest-creds="${{ gitea.actor }}:${{ secrets.REGISTRY_TOKEN }}" \
            docker-daemon:${{ steps.meta.outputs.image }}:latest \
            docker://${{ steps.meta.outputs.image }}:latest
          echo "Images pushed successfully"

  security-scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: gitea.ref == 'refs/heads/main'
    steps:
      - name: Run Trivy vulnerability scanner
        run: |
          # Install trivy directly
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee -a /etc/apt/sources.list.d/trivy.list
          apt-get update -qq
          apt-get install -y -qq trivy > /dev/null

          # Run scan on the image (no auth needed for insecure registry)
          trivy image --insecure --format table \
            --severity HIGH,CRITICAL \
            ${{ env.REGISTRY }}/${{ gitea.repository_owner }}/${{ env.IMAGE_NAME }}:latest || true

          echo "Trivy scan completed"