apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        ports:
        - containerPort: 8080
          hostPort: 30080
          protocol: TCP
