apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    spec:
      containers:
      - name: argocd-server
        args:
        - /usr/local/bin/argocd-server
        - --content-security-policy=
        ports:
        - containerPort: 8080
          hostPort: 30080
          protocol: TCP
