apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: applications
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    spec:
      containers:
      - name: gitea
        ports:
        - containerPort: 3000
          hostPort: 30082
          name: http
          protocol: TCP
